require("plugins.lazy")

require("core.options")
require("core.keymaps")
require("plugins.neo-tree")
require("plugins.comment")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.telescope")
require("plugins.gitsigns")
require("plugins.noice")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.alpha-nvim")
require("plugins.mod-lualine")
